yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='posts_slug'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name='Название группы',
        max_length=200
    )
    slug = models.SlugField(
        verbose_name='Обозначение',
        unique=True
    )
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        # выводим текст поста
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(verbose_name='Текст комментария')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации комментария'
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписка',
    )

    def __str__(self):
        return f'{self.user.username} подписан на {self.author.username}'

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_following'
            )
        ]
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = (
            'text',
            'group',
            'image'
        )
        labels = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = (
            'text',
        )
        labels = {
            'text': 'Текст комментария'
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow
from .paginator import paginator_page


def index(request):
    return render(request, 'posts/index.html', {
        'page_obj': paginator_page(request, Post.objects.all()),
    })


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    return render(request, 'posts/group_list.html', {
        'group': group,
        'page_obj': paginator_page(request, group.posts.all())
    })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    follow = (
        request.user.is_authenticated
        and request.user.username != username
        and Follow.objects.filter(
            author=author,
            user=request.user).exists())
    return render(request, 'posts/profile.html', {
        'author': author,
        'page_obj': paginator_page(request, author.posts.all()),
        'following': follow
    })


def post_detail(request, post_id):
    return render(request, 'posts/post_detail.html', {
        'post': get_object_or_404(Post, id=post_id),
        'form': CommentForm(request.POST or None),
    })


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {
            'form': form
        })
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', post.author)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', {
        'form': form, 'is_edit': True, 'post': post
    })


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_follow = Post.objects.filter(
        author__following__user=request.user
    )
    return render(
        request, 'posts/follow.html',
        {'page_obj': paginator_page(request, post_follow)})


@login_required
def profile_follow(request, username):
    if username != request.user.username:
        author = get_object_or_404(User, username=username)
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        Follow,
        author__username=username,
        user=request.user
    ).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% load user_filters %}

{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock title %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data" {% if action_url %} action="{% url action_url %}" {% endif %}>
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
           </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}
  Подписки
{% endblock %}

{% block content %}
{% load cache %}
{% load thumbnail %}
  <div class='container py-5'>
    {% include 'posts/includes/switcher.html' with follow=True %}
  {% cache 20 index_page %}
  <h1>Главная страница</h1>
  <h4>Последние записи пользователей</h4>
  {% for post in page_obj %}
    {% include 'posts/includes/post.html' %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endcache %} 

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  Группа {{ group }}
{% endblock %}

{% block content %}
{% load thumbnail%}
 <div class='container py-5'>
  <h1>{{ group.title }}</h1>
  <h4> {{ group.description|linebreaks }} </h4>
  {% for post in page_obj %}
    {% include 'posts/includes/post.html' with non_group=True%}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
 
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %} 

{% block title %} 
  Подписки 
{% endblock %} 

{% block content %} 
{% load cache %} 
{% load thumbnail %} 
  <div class='container py-5'> 
    {% include 'posts/includes/switcher.html' with index=True %} 
  {% cache 20 index_page with page_obj %} 
    <h1>Главная страница</h1> 
    <h4>Последние записи пользователей</h4> 
  {% for post in page_obj %}
    {% include 'posts/includes/post.html'%}
  {% if not forloop.last %}<hr>{% endif %} 
{% endfor %} 
  {% include 'posts/includes/paginator.html' %} 
{% endcache %}  
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ post.text|truncatechars:30 }} 
{% endblock %}

{% block content %}
{% load thumbnail %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}  
        </li>
        <li class="list-group-item">
          {{ post.group.title }}
          {% if post.group %}   
            <a href="{% url 'posts:posts_slug' post.group.slug %}">все записи группы</a>
          {% endif %}
        </li>
        <li class="list-group-item">
          {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Записей: {{ post.author.posts.count }}
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr  }}</p>
      <p>
        {% if request.user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
          </a>
        {% endif %}
        {% include 'posts/includes/comment.html' %}
      </p>
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
  Профайл пользователя {{author.username}}
{% endblock %}

{% block content %}
{% load thumbnail %}
<div class="mb-5">
  <div class="container py-5">        
    <h1>Все посты пользователя {{ author.first_name }} {{ author.last_name }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    <h4>Количество подписчиков: {{author.following.count}}</h4>
    <h4>Количество подписок: {{author.follower.count}}</h4>
    <h4>Количество комментариев: {{author.comments.count}}</h4>
    {% if user != author and user.is_authenticated %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}"
          role="button"
        >
          Отписаться
        </a>
      {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}"
        role="button"
      >
        Подписаться
      </a>
      {% endif %}
   {% endif %}
    {% for post in page_obj %}
      {% include 'posts/includes/post.html' %}
      {% if not forloop.last %} <hr> {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
</div>
{% endblock %}